# Generated by Django 3.2.12 on 2022-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millisecond', models.PositiveBigIntegerField()),
                ('short_code', models.CharField(max_length=7)),
                ('main_url', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'tiny_url',
            },
        ),
    ]
