# Generated by Django 3.2.12 on 2022-03-01 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tinyurl_main_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinyurl',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
