# Generated by Django 3.2.12 on 2022-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tinyurl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
